-- AlterTable
ALTER TABLE "Interview" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "interviewId" TEXT,
ADD COLUMN     "isDraft" BOOLEAN,
ADD COLUMN     "secretPin" TEXT,
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
